### ISSUE TITLE
Add support for prereleases

### ISSUE THREAD

**Issue by theotherp** [binhex/arch-nzbhydra2#8]
I'll add support for prereleases in the next version. These can be determined by the property `prerelease` of the GitHub release (e.g. https://api.github.com/repos/theotherp/nzbhydra2/releases/latest).

Would it be possible for the regular container to not update to these and add a new container or tag for the latest prerelease? 

To be honest I'm not aware of the build process and even how the containers are installed, so I'm not sure if this would even be possible.

Thanks!

**Comment by binhex** [comment]
Sorry for the delay in responding, so i have code in place to auto build a new docker image when a new github 'release' is created, at the moment i dont differentiate between a github 'pre-release' and a normal 'release' so if you create a new release, either as a pre-release or normal release then a new docker image will be built - you can see the list of tagged docker images here (docker tags are taken from the release tag name):- https://hub.docker.com/repository/docker/binhex/arch-nzbhydra2/tags?page=1

I couild enhance my auto build code further so that i can decide whether to build pre-releases (or not) but right now thats not in place and its a blanket always build , i hope that answers your question, if not feel free to ask away.
